13-query
DinaKobrik/dz_JS_base pull request #4
Opened 2024-09-16 19:44 UTC by DinaKobrik

2024-09-19 09:22 UTC, DinaKobrik commented
В 15 дз не понимаю как исправить момент: после удаления задачи выводит первой задачу "Вытереть посуду", хотя замен задачи происходит ниже. В замене создается копия, чтоб изменения не затронули вывод остальных функций, но на removeTask это не действует.

2024-09-20 15:00 UTC, GitEsense requested changes
По `15-dz` в целом "ок", но лучше "доработать", оставил комментарии
По `13-dz` Необходимо немного переделать

2024-09-20 15:00 UTC, GitEsense commented on 13-dz/app.js
> +  },
Там у нас не пойдёт, мы изначально не знаем какие у нас ключи есть доступные
скажем так - функция должна работать верно с объектом вида:
```js
const obj = {
   name: 'Vasya',
   phone: '88005553535'
}

function query(obj) {
    // Код Вашей программы
}

console.log(query(obj)); // name=Vasya&phone=8800553535
```

так и вида
```js
const obj = {
   id: 22,
   type: 'string',
   value: 'Новая строка',
   createdAt: Date.now(),
   updateAt: null
}
```

2024-09-20 15:00 UTC, GitEsense commented on 15-dz/app.js
> +    const id = this.tasks.length + 1;
Лучше id присваивать не по длине массива, а по внешнему каунтеру (например свойство того же объекта lastId
```js
const toDoList = {
   tasks: [],
   lastId: 0,
   addTask: function (title, priority) {
       this.tasks.push({ title, id: ++this.lastId, priority });
  },
}
}
```
Так же можно провести проверки и в идеале вообще принимать на вход "объект" (там будет удобнее работать с множеством свойств)

2024-09-20 15:00 UTC, GitEsense commented on 15-dz/app.js
> +    const taskIndex = this.tasks.findIndex(task => task.id === id);
Можно воспользоваться функцией find, тогда будет сильно проще и идти от обратного, но лучше работать с объектом , станет так же сильно проще
```js
function updateTask(id, title= null, priority= null) {
   const task= this.tasks.task(task => task.id === id);
    if(!task) {
        return;
    }
    if(title) {
       task.title= title
     }
    if(priority) {
        task.priority = priority
     }
}

2024-09-21 10:15 UTC, DinaKobrik commented on 15-dz/app.js
> +    const taskIndex = this.tasks.findIndex(task => task.id === id);
Через find у меня при первом выводе сразу заменялась первая задача, прибегла к findIndex чтоб создать копию и измененная задача выводилась только после вызова функции updateTask, но она почему то все равно выводится уже после вызова removeTask
![Снимок экрана 2024-09-21 в 13 12 26](https://github.com/user-attachments/assets/d8fd938e-d75f-4919-a666-13826464d850)

2024-09-21 10:25 UTC, GitEsense commented on 15-dz/app.js
> +    const taskIndex = this.tasks.findIndex(task => task.id === id);
Вы смотрите через консоль браузера и он показывает состояние задач на момент "развертывания" объекта, чтобы видеть , реальное состояние, делайте на вывод "копию массива" текущего состояния, т.е.
Вместо console.log(toDoList.tasks) напишите console.log(...toDoList.tasks) или 
console.log([...toDoList.tasks])

2024-09-24 13:17 UTC, GitEsense approved these changes

2024-09-24 13:17 UTC, GitEsense commented on 13-dz/app.js
> +console.log(query(obj));
Отлично, ещё можно было чуточку упростить
```js
const toQueryString = (params) => Object.entries(params).map(x => x.join('=')).join('&')
```

2024-09-30 09:26 UTC, merged